defaults:
  - _self_

gpus: ???
data_path: ???
task: ???
seed: 3074

trainer:
  _target_: pytorch_lightning.Trainer
  gpus: ${gpus}
  precision: 32
  benchmark: true
  num_sanity_val_steps: 0
  max_epochs: 400000
  val_check_interval: null
  gradient_clip_val: 0.0

module:
  _target_: cec.module.RobomimicImitationModule
  policy:
    _target_: cec.policy.cec_robomimic.CECRoboMimicPolicy
    feature_encoders:
      robot0_eef_pos:
        _target_: cec.nn.feature.identity.DummyIdentity
        input_dim: 3
      robot0_eef_quat:
        _target_: cec.nn.feature.identity.DummyIdentity
        input_dim: 4
      robot0_gripper_qpos:
        _target_: cec.nn.feature.identity.DummyIdentity
        input_dim: 2
      agentview_image:
        _target_: cec.nn.feature.robomimic_rgb.RoboMimicRgbEncoder
      robot0_eye_in_hand_image:
        _target_: cec.nn.feature.robomimic_rgb.RoboMimicRgbEncoder
    robosuite_action_size: 7
    hidden_size: 400
    timesteps: 200
    use_pointwise_layer: true
    pointwise_ratio: 4
    pointwise_use_activation: true
    attention_heads: 8
    attention_memory_size: 400
    n_transformer_blocks: 2
    pi_head_kwargs:
      hidden_depth: 1
      hidden_dim: 400
    subsample_every: 1
  lr: 1e-4
  lr_warmup_steps: 0
  lr_cosine_steps: 20000
  lr_cosine_min: 1e-5
  weight_decay: 0.0

data_module:
  _target_: cec.data.RoboMimicDataModule
  task: ${task}
  data_parent_dir: ${data_path}
  ctx_len: 200
  batch_size: 1
  val_batch_size: 1
  dataloader_num_workers: 8
  n_episodes_per_level: [1, 5]
  seed: ${seed}
  shuffle: true
  cache_in_mem: false
  precision: 32

hydra:
  job:
    chdir: true
  run:
    dir: "."
  output_subdir: null
