# @package _global_

data_module:
  ctx_len: -1
  batch_size: 1
  val_batch_size: 1
  task: dmlab_irreversible_path
  train_levels: [1,3,5,7]
  num_trajs: 100
  n_episodes_per_level: [1, 3]
  shuffle: false
  even_spacing: true
  adapted: true
