# @package _global_

module:
  policy:
    timesteps: 1600
    attention_memory_size: 3200

data_module:
  ctx_len: 1600
  batch_size: 2
  val_batch_size: 2
  task: dmlab_irreversible_path
  train_levels: [1,3,5,7,9]
  num_trajs: 100
  n_episodes_per_level: [1,3]
  adapted: true
