# @package _global_

data_module:
  ctx_len: -1
  batch_size: 2
  val_batch_size: 2
  task: dmlab_goal_large
  train_levels: [5,10,15]
  num_trajs: 100
  n_episodes_per_level: [1, 4]
  shuffle: false
  even_spacing: true
  adapted: true
