# @package _global_

module:
  policy:
    timesteps: 500
    attention_memory_size: 1000

data_module:
  ctx_len: 500
  batch_size: 4
  val_batch_size: 4
  task: dmlab_goal_large
  train_levels: [5,10,15]
  num_trajs: 100
  n_episodes_per_level: [1,5]
  adapted: true
