# @package _global_

data_module:
  ctx_len: -1
  batch_size: 16
  val_batch_size: 16
  task: dmlab_goal_large
  train_levels: [20]
  num_trajs: 300
  n_episodes_per_level: 1
  shuffle: true
  even_spacing: false
  adapted: false
