# @package _global_

module:
  policy:
    timesteps: 400
    attention_memory_size: 800

data_module:
  ctx_len: 400
  batch_size: 4
  val_batch_size: 4
  task: dmlab_watermaze
  train_levels: [580]
  num_trajs: 300
  n_episodes_per_level: 9
  shuffle: false
  even_spacing: true
  adapted: false
